#include "Item.h"

#include "ItemPickaxe.h"

Item* Item::iron_shovel = new Item();
Item* Item::iron_pickaxe = new ItemPickaxe(ItemTool::ToolMaterial::IRON);
Item* Item::iron_axe = new Item();
Item* Item::flint_and_steel = new Item();
Item* Item::apple = new Item();
Item* Item::bow = new Item();
Item* Item::arrow = new Item();
Item* Item::coal = new Item();
Item* Item::diamond = new Item();
Item* Item::iron_ingot = new Item();
Item* Item::gold_ingot = new Item();
Item* Item::iron_sword = new Item();
Item* Item::wooden_sword = new Item();
Item* Item::wooden_shovel = new Item();
Item* Item::wooden_pickaxe = new ItemPickaxe(ItemTool::ToolMaterial::WOOD);
Item* Item::wooden_axe = new Item();
Item* Item::stone_sword = new Item();
Item* Item::stone_shovel = new Item();
Item* Item::stone_pickaxe = new ItemPickaxe(ItemTool::ToolMaterial::STONE);
Item* Item::stone_axe = new Item();
Item* Item::diamond_sword = new Item();
Item* Item::diamond_shovel = new Item();
Item* Item::diamond_pickaxe = new ItemPickaxe(ItemTool::ToolMaterial::DIAMOND);
Item* Item::diamond_axe = new Item();
Item* Item::stick = new Item();
Item* Item::bowl = new Item();
Item* Item::mushroom_stew = new Item();
Item* Item::golden_sword = new Item();
Item* Item::golden_shovel = new Item();
Item* Item::golden_pickaxe = new ItemPickaxe(ItemTool::ToolMaterial::GOLD);
Item* Item::golden_axe = new Item();
Item* Item::string = new Item();
Item* Item::feather = new Item();
Item* Item::gunpowder = new Item();
Item* Item::wooden_hoe = new Item();
Item* Item::stone_hoe = new Item();
Item* Item::iron_hoe = new Item();
Item* Item::diamond_hoe = new Item();
Item* Item::golden_hoe = new Item();
Item* Item::wheat_seeds = new Item();
Item* Item::wheat = new Item();
Item* Item::bread = new Item();
Item* Item::leather_helmet = new Item();
Item* Item::leather_chestplate = new Item();
Item* Item::leather_leggings = new Item();
Item* Item::leather_boots = new Item();
Item* Item::chainmail_helmet = new Item();
Item* Item::chainmail_chestplate = new Item();
Item* Item::chainmail_leggings = new Item();
Item* Item::chainmail_boots = new Item();
Item* Item::iron_helmet = new Item();
Item* Item::iron_chestplate = new Item();
Item* Item::iron_leggings = new Item();
Item* Item::iron_boots = new Item();
Item* Item::diamond_helmet = new Item();
Item* Item::diamond_chestplate = new Item();
Item* Item::diamond_leggings = new Item();
Item* Item::diamond_boots = new Item();
Item* Item::golden_helmet = new Item();
Item* Item::golden_chestplate = new Item();
Item* Item::golden_leggings = new Item();
Item* Item::golden_boots = new Item();
Item* Item::flint = new Item();
Item* Item::porkchop = new Item();
Item* Item::cooked_porkchop = new Item();
Item* Item::painting = new Item();
Item* Item::golden_apple = new Item();
Item* Item::sign = new Item();
Item* Item::wooden_door = new Item();
Item* Item::bucket = new Item();
Item* Item::water_bucket = new Item();
Item* Item::lava_bucket = new Item();
Item* Item::minecart = new Item();
Item* Item::saddle = new Item();
Item* Item::iron_door = new Item();
Item* Item::redstone = new Item();
Item* Item::snowball = new Item();
Item* Item::boat = new Item();
Item* Item::leather = new Item();
Item* Item::milk_bucket = new Item();
Item* Item::brick = new Item();
Item* Item::clay_ball = new Item();
Item* Item::reeds = new Item();
Item* Item::paper = new Item();
Item* Item::book = new Item();
Item* Item::slime_ball = new Item();
Item* Item::chest_minecart = new Item();
Item* Item::furnace_minecart = new Item();
Item* Item::egg = new Item();
Item* Item::compass = new Item();
Item* Item::fishing_rod = new Item();
Item* Item::clock = new Item();
Item* Item::glowstone_dust = new Item();
Item* Item::fish = new Item();
Item* Item::cooked_fish = new Item();
Item* Item::dye = new Item();
Item* Item::bone = new Item();
Item* Item::sugar = new Item();
Item* Item::cake = new Item();
Item* Item::bed = new Item();
Item* Item::repeater = new Item();
Item* Item::cookie = new Item();
Item* Item::filled_map = new Item();
Item* Item::shears = new Item();
Item* Item::melon = new Item();
Item* Item::pumpkin_seeds = new Item();
Item* Item::melon_seeds = new Item();
Item* Item::beef = new Item();
Item* Item::cooked_beef = new Item();
Item* Item::chicken = new Item();
Item* Item::cooked_chicken = new Item();
Item* Item::rotten_flesh = new Item();
Item* Item::ender_pearl = new Item();
Item* Item::blaze_rod = new Item();
Item* Item::ghast_tear = new Item();
Item* Item::gold_nugget = new Item();
Item* Item::nether_wart = new Item();
Item* Item::potion = new Item();
Item* Item::glass_bottle = new Item();
Item* Item::spider_eye = new Item();
Item* Item::fermented_spider_eye = new Item();
Item* Item::blaze_powder = new Item();
Item* Item::magma_cream = new Item();
Item* Item::brewing_stand = new Item();
Item* Item::cauldron = new Item();
Item* Item::ender_eye = new Item();
Item* Item::speckled_melon = new Item();
Item* Item::spawn_egg = new Item();
Item* Item::experience_bottle = new Item();
Item* Item::fire_charge = new Item();
Item* Item::writable_book = new Item();
Item* Item::written_book = new Item();
Item* Item::emerald = new Item();
Item* Item::item_frame = new Item();
Item* Item::flower_pot = new Item();
Item* Item::carrot = new Item();
Item* Item::potato = new Item();
Item* Item::baked_potato = new Item();
Item* Item::poisonous_potato = new Item();
Item* Item::map = new Item();
Item* Item::golden_carrot = new Item();
Item* Item::skull = new Item();
Item* Item::carrot_on_a_stick = new Item();
Item* Item::nether_star = new Item();
Item* Item::pumpkin_pie = new Item();
Item* Item::fireworks = new Item();
Item* Item::firework_charge = new Item();
Item* Item::enchanted_book = new Item();
Item* Item::comparator = new Item();
Item* Item::netherbrick = new Item();
Item* Item::quartz = new Item();
Item* Item::tnt_minecart = new Item();
Item* Item::hopper_minecart = new Item();
Item* Item::prismarine_shard = new Item();
Item* Item::prismarine_crystals = new Item();
Item* Item::rabbit = new Item();
Item* Item::cooked_rabbit = new Item();
Item* Item::rabbit_stew = new Item();
Item* Item::rabbit_foot = new Item();
Item* Item::rabbit_hide = new Item();
Item* Item::armor_stand = new Item();
Item* Item::iron_horse_armor = new Item();
Item* Item::golden_horse_armor = new Item();
Item* Item::diamond_horse_armor = new Item();
Item* Item::lead = new Item();
Item* Item::name_tag = new Item();
Item* Item::command_block_minecart = new Item();
Item* Item::mutton = new Item();
Item* Item::cooked_mutton = new Item();
Item* Item::banner = new Item();
Item* Item::spruce_door = new Item();
Item* Item::birch_door = new Item();
Item* Item::jungle_door = new Item();
Item* Item::acacia_door = new Item();
Item* Item::dark_oak_door = new Item();
Item* Item::record_13 = new Item();
Item* Item::record_cat = new Item();
Item* Item::record_blocks = new Item();
Item* Item::record_chirp = new Item();
Item* Item::record_far = new Item();
Item* Item::record_mall = new Item();
Item* Item::record_mellohi = new Item();
Item* Item::record_stal = new Item();
Item* Item::record_strad = new Item();
Item* Item::record_ward = new Item();
Item* Item::record_11 = new Item();
Item* Item::record_wait = new Item();

void Item::registerItem(ushort_t id, string_t name, Item *item) {
    idToName.insert({id, name});
    idToItem.insert({id, item});
    nameToId.insert({name, id,});
    nameToItem.insert({name, item});
}

void Item::registerItems() {
    registerItem(256, "iron_shovel", iron_shovel);
    registerItem(257, "iron_pickaxe", iron_pickaxe);
    registerItem(258, "iron_axe", iron_axe);
    registerItem(259, "flint_and_steel", flint_and_steel);
    registerItem(260, "apple", apple);
    registerItem(261, "bow", bow);
    registerItem(262, "arrow", arrow);
    registerItem(263, "coal", coal);
    registerItem(264, "diamond", diamond);
    registerItem(265, "iron_ingot", iron_ingot);
    registerItem(266, "gold_ingot", gold_ingot);
    registerItem(267, "iron_sword", iron_sword);
    registerItem(268, "wooden_sword", wooden_sword);
    registerItem(269, "wooden_shovel", wooden_shovel);
    registerItem(270, "wooden_pickaxe", wooden_pickaxe);
    registerItem(271, "wooden_axe", wooden_axe);
    registerItem(272, "stone_sword", stone_sword);
    registerItem(273, "stone_shovel", stone_shovel);
    registerItem(274, "stone_pickaxe", stone_pickaxe);
    registerItem(275, "stone_axe", stone_axe);
    registerItem(276, "diamond_sword", diamond_sword);
    registerItem(277, "diamond_shovel", diamond_shovel);
    registerItem(278, "diamond_pickaxe", diamond_pickaxe);
    registerItem(279, "diamond_axe", diamond_axe);
    registerItem(280, "stick", stick);
    registerItem(281, "bowl", bowl);
    registerItem(282, "mushroom_stew", mushroom_stew);
    registerItem(283, "golden_sword", golden_sword);
    registerItem(284, "golden_shovel", golden_shovel);
    registerItem(285, "golden_pickaxe", golden_pickaxe);
    registerItem(286, "golden_axe", golden_axe);
    registerItem(287, "string", string);
    registerItem(288, "feather", feather);
    registerItem(289, "gunpowder", gunpowder);
    registerItem(290, "wooden_hoe", wooden_hoe);
    registerItem(291, "stone_hoe", stone_hoe);
    registerItem(292, "iron_hoe", iron_hoe);
    registerItem(293, "diamond_hoe", diamond_hoe);
    registerItem(294, "golden_hoe", golden_hoe);
    registerItem(295, "wheat_seeds", wheat_seeds);
    registerItem(296, "wheat", wheat);
    registerItem(297, "bread", bread);
    registerItem(298, "leather_helmet", leather_helmet);
    registerItem(299, "leather_chestplate", leather_chestplate);
    registerItem(300, "leather_leggings", leather_leggings);
    registerItem(301, "leather_boots", leather_boots);
    registerItem(302, "chainmail_helmet", chainmail_helmet);
    registerItem(303, "chainmail_chestplate", chainmail_chestplate);
    registerItem(304, "chainmail_leggings", chainmail_leggings);
    registerItem(305, "chainmail_boots", chainmail_boots);
    registerItem(306, "iron_helmet", iron_helmet);
    registerItem(307, "iron_chestplate", iron_chestplate);
    registerItem(308, "iron_leggings", iron_leggings);
    registerItem(309, "iron_boots", iron_boots);
    registerItem(310, "diamond_helmet", diamond_helmet);
    registerItem(311, "diamond_chestplate", diamond_chestplate);
    registerItem(312, "diamond_leggings", diamond_leggings);
    registerItem(313, "diamond_boots", diamond_boots);
    registerItem(314, "golden_helmet", golden_helmet);
    registerItem(315, "golden_chestplate", golden_chestplate);
    registerItem(316, "golden_leggings", golden_leggings);
    registerItem(317, "golden_boots", golden_boots);
    registerItem(318, "flint", flint);
    registerItem(319, "porkchop", porkchop);
    registerItem(320, "cooked_porkchop", cooked_porkchop);
    registerItem(321, "painting", painting);
    registerItem(322, "golden_apple", golden_apple);
    registerItem(323, "sign", sign);
    registerItem(324, "wooden_door", wooden_door);
    registerItem(325, "bucket", bucket);
    registerItem(326, "water_bucket", water_bucket);
    registerItem(327, "lava_bucket", lava_bucket);
    registerItem(328, "minecart", minecart);
    registerItem(329, "saddle", saddle);
    registerItem(330, "iron_door", iron_door);
    registerItem(331, "redstone", redstone);
    registerItem(332, "snowball", snowball);
    registerItem(333, "boat", boat);
    registerItem(334, "leather", leather);
    registerItem(335, "milk_bucket", milk_bucket);
    registerItem(336, "brick", brick);
    registerItem(337, "clay_ball", clay_ball);
    registerItem(338, "reeds", reeds);
    registerItem(339, "paper", paper);
    registerItem(340, "book", book);
    registerItem(341, "slime_ball", slime_ball);
    registerItem(342, "chest_minecart", chest_minecart);
    registerItem(343, "furnace_minecart", furnace_minecart);
    registerItem(344, "egg", egg);
    registerItem(345, "compass", compass);
    registerItem(346, "fishing_rod", fishing_rod);
    registerItem(347, "clock", clock);
    registerItem(348, "glowstone_dust", glowstone_dust);
    registerItem(349, "fish", fish);
    registerItem(350, "cooked_fish", cooked_fish);
    registerItem(351, "dye", dye);
    registerItem(352, "bone", bone);
    registerItem(353, "sugar", sugar);
    registerItem(354, "cake", cake);
    registerItem(355, "bed", bed);
    registerItem(356, "repeater", repeater);
    registerItem(357, "cookie", cookie);
    registerItem(358, "filled_map", filled_map);
    registerItem(359, "shears", shears);
    registerItem(360, "melon", melon);
    registerItem(361, "pumpkin_seeds", pumpkin_seeds);
    registerItem(362, "melon_seeds", melon_seeds);
    registerItem(363, "beef", beef);
    registerItem(364, "cooked_beef", cooked_beef);
    registerItem(365, "chicken", chicken);
    registerItem(366, "cooked_chicken", cooked_chicken);
    registerItem(367, "rotten_flesh", rotten_flesh);
    registerItem(368, "ender_pearl", ender_pearl);
    registerItem(369, "blaze_rod", blaze_rod);
    registerItem(370, "ghast_tear", ghast_tear);
    registerItem(371, "gold_nugget", gold_nugget);
    registerItem(372, "nether_wart", nether_wart);
    registerItem(373, "potion", potion);
    registerItem(374, "glass_bottle", glass_bottle);
    registerItem(375, "spider_eye", spider_eye);
    registerItem(376, "fermented_spider_eye", fermented_spider_eye);
    registerItem(377, "blaze_powder", blaze_powder);
    registerItem(378, "magma_cream", magma_cream);
    registerItem(379, "brewing_stand", brewing_stand);
    registerItem(380, "cauldron", cauldron);
    registerItem(381, "ender_eye", ender_eye);
    registerItem(382, "speckled_melon", speckled_melon);
    registerItem(383, "spawn_egg", spawn_egg);
    registerItem(384, "experience_bottle", experience_bottle);
    registerItem(385, "fire_charge", fire_charge);
    registerItem(386, "writable_book", writable_book);
    registerItem(387, "written_book", written_book);
    registerItem(388, "emerald", emerald);
    registerItem(389, "item_frame", item_frame);
    registerItem(390, "flower_pot", flower_pot);
    registerItem(391, "carrot", carrot);
    registerItem(392, "potato", potato);
    registerItem(393, "baked_potato", baked_potato);
    registerItem(394, "poisonous_potato", poisonous_potato);
    registerItem(395, "map", map);
    registerItem(396, "golden_carrot", golden_carrot);
    registerItem(397, "skull", skull);
    registerItem(398, "carrot_on_a_stick", carrot_on_a_stick);
    registerItem(399, "nether_star", nether_star);
    registerItem(400, "pumpkin_pie", pumpkin_pie);
    registerItem(401, "fireworks", fireworks);
    registerItem(402, "firework_charge", firework_charge);
    registerItem(403, "enchanted_book", enchanted_book);
    registerItem(404, "comparator", comparator);
    registerItem(405, "netherbrick", netherbrick);
    registerItem(406, "quartz", quartz);
    registerItem(407, "tnt_minecart", tnt_minecart);
    registerItem(408, "hopper_minecart", hopper_minecart);
    registerItem(409, "prismarine_shard", prismarine_shard);
    registerItem(410, "prismarine_crystals", prismarine_crystals);
    registerItem(411, "rabbit", rabbit);
    registerItem(412, "cooked_rabbit", cooked_rabbit);
    registerItem(413, "rabbit_stew", rabbit_stew);
    registerItem(414, "rabbit_foot", rabbit_foot);
    registerItem(415, "rabbit_hide", rabbit_hide);
    registerItem(416, "armor_stand", armor_stand);
    registerItem(417, "iron_horse_armor", iron_horse_armor);
    registerItem(418, "golden_horse_armor", golden_horse_armor);
    registerItem(419, "diamond_horse_armor", diamond_horse_armor);
    registerItem(420, "lead", lead);
    registerItem(421, "name_tag", name_tag);
    registerItem(422, "command_block_minecart", command_block_minecart);
    registerItem(423, "mutton", mutton);
    registerItem(424, "cooked_mutton", cooked_mutton);
    registerItem(425, "banner", banner);
    registerItem(427, "spruce_door", spruce_door);
    registerItem(428, "birch_door", birch_door);
    registerItem(429, "jungle_door", jungle_door);
    registerItem(430, "acacia_door", acacia_door);
    registerItem(431, "dark_oak_door", dark_oak_door);
    registerItem(2256, "record_13", record_13);
    registerItem(2257, "record_cat", record_cat);
    registerItem(2258, "record_blocks", record_blocks);
    registerItem(2259, "record_chirp", record_chirp);
    registerItem(2260, "record_far", record_far);
    registerItem(2261, "record_mall", record_mall);
    registerItem(2262, "record_mellohi", record_mellohi);
    registerItem(2263, "record_stal", record_stal);
    registerItem(2264, "record_strad", record_strad);
    registerItem(2265, "record_ward", record_ward);
    registerItem(2266, "record_11", record_11);
    registerItem(2267, "record_wait", record_wait);
}

void Item::deregisterItems() {
    std::unordered_map<string_t, Item*>::iterator it;

    for(it = nameToItem.begin(); it != nameToItem.end(); ++it)
        delete it->second;
}

Item *Item::getItem(ubyte_t id) {
    return idToItem[id];
}

Item *Item::getItem(string_t name) {
    return nameToItem[name];
}

ushort_t Item::getItemId(string_t name) {
    return nameToId[name];
}

string_t Item::getItemName(ushort_t id) {
    return idToName[id];
}

Item::Item() {}

std::unordered_map<ushort_t, string_t> Item::idToName;
std::unordered_map<ushort_t, Item*> Item::idToItem;
std::unordered_map<string_t, ushort_t> Item::nameToId;
std::unordered_map<string_t, Item*> Item::nameToItem;
