#include "Block.h"

#include "BlockAir.h"

Block* Block::air;
Block* Block::stone;
Block* Block::grass;
Block* Block::dirt;
Block* Block::cobblestone;
Block* Block::planks;
Block* Block::sapling;
Block* Block::bedrock;
Block* Block::flowing_water;
Block* Block::water;
Block* Block::flowing_lava;
Block* Block::lava;
Block* Block::sand;
Block* Block::gravel;
Block* Block::gold_ore;
Block* Block::iron_ore;
Block* Block::coal_ore;
Block* Block::log;
Block* Block::leaves;
Block* Block::sponge;
Block* Block::glass;
Block* Block::lapis_ore;
Block* Block::lapis_block;
Block* Block::dispenser;
Block* Block::sandstone;
Block* Block::noteblock;
Block* Block::bed;
Block* Block::golden_rail;
Block* Block::detector_rail;
Block* Block::sticky_piston;
Block* Block::web;
Block* Block::tallgrass;
Block* Block::deadbush;
Block* Block::piston;
Block* Block::piston_head;
Block* Block::wool;
Block* Block::piston_extension;
Block* Block::yellow_flower;
Block* Block::red_flower;
Block* Block::brown_mushroom;
Block* Block::red_mushroom;
Block* Block::gold_block;
Block* Block::iron_block;
Block* Block::double_stone_slab;
Block* Block::stone_slab;
Block* Block::brick_block;
Block* Block::tnt;
Block* Block::bookshelf;
Block* Block::mossy_cobblestone;
Block* Block::obsidian;
Block* Block::torch;
Block* Block::fire;
Block* Block::mob_spawner;
Block* Block::oak_stairs;
Block* Block::chest;
Block* Block::redstone_wire;
Block* Block::diamond_ore;
Block* Block::diamond_block;
Block* Block::crafting_table;
Block* Block::wheat;
Block* Block::farmland;
Block* Block::furnace;
Block* Block::lit_furnace;
Block* Block::standing_sign;
Block* Block::wooden_door;
Block* Block::ladder;
Block* Block::rail;
Block* Block::stone_stairs;
Block* Block::wall_sign;
Block* Block::lever;
Block* Block::stone_pressure_plate;
Block* Block::iron_door;
Block* Block::wooden_pressure_plate;
Block* Block::redstone_ore;
Block* Block::lit_redstone_ore;
Block* Block::unlit_redstone_torch;
Block* Block::redstone_torch;
Block* Block::stone_button;
Block* Block::snow_layer;
Block* Block::ice;
Block* Block::snow;
Block* Block::cactus;
Block* Block::clay;
Block* Block::reeds;
Block* Block::jukebox;
Block* Block::oak_fence;
Block* Block::pumpkin;
Block* Block::netherrack;
Block* Block::soul_sand;
Block* Block::glowstone;
Block* Block::portal;
Block* Block::lit_pumpkin;
Block* Block::cake;
Block* Block::unpowered_repeater;
Block* Block::powered_repeater;
Block* Block::stained_glass;
Block* Block::trapdoor;
Block* Block::monster_egg;
Block* Block::stonebrick;
Block* Block::brown_mushroom_block;
Block* Block::red_mushroom_block;
Block* Block::iron_bars;
Block* Block::glass_pane;
Block* Block::melon_block;
Block* Block::pumpkin_stem;
Block* Block::melon_stem;
Block* Block::vine;
Block* Block::oak_fence_gate;
Block* Block::brick_stairs;
Block* Block::stone_brick_stairs;
Block* Block::mycelium;
Block* Block::waterlily;
Block* Block::nether_brick;
Block* Block::nether_brick_fence;
Block* Block::nether_brick_stairs;
Block* Block::nether_wart;
Block* Block::enchanting_table;
Block* Block::brewing_stand;
Block* Block::cauldron;
Block* Block::end_portal;
Block* Block::end_portal_frame;
Block* Block::end_stone;
Block* Block::dragon_egg;
Block* Block::redstone_lamp;
Block* Block::lit_redstone_lamp;
Block* Block::double_wooden_slab;
Block* Block::wooden_slab;
Block* Block::cocoa;
Block* Block::sandstone_stairs;
Block* Block::emerald_ore;
Block* Block::ender_chest;
Block* Block::tripwire_hook;
Block* Block::tripwire;
Block* Block::emerald_block;
Block* Block::spruce_stairs;
Block* Block::birch_stairs;
Block* Block::jungle_stairs;
Block* Block::command_block;
Block* Block::beacon;
Block* Block::cobblestone_wall;
Block* Block::flower_pot;
Block* Block::carrots;
Block* Block::potatoes;
Block* Block::wooden_button;
Block* Block::skull;
Block* Block::anvil;
Block* Block::trapped_chest;
Block* Block::light_weighted_pressure_plate;
Block* Block::heavy_weighted_pressure_plate;
Block* Block::unpowered_comparator;
Block* Block::powered_comparator;
Block* Block::daylight_detector;
Block* Block::redstone_block;
Block* Block::quartz_ore;
Block* Block::hopper;
Block* Block::quartz_block;
Block* Block::quartz_stairs;
Block* Block::activator_rail;
Block* Block::dropper;
Block* Block::stained_hardened_clay;
Block* Block::stained_glass_pane;
Block* Block::leaves2;
Block* Block::log2;
Block* Block::acacia_stairs;
Block* Block::dark_oak_stairs;
Block* Block::slime_block;
Block* Block::barrier;
Block* Block::iron_trapdoor;
Block* Block::prismarine;
Block* Block::sea_lantern;
Block* Block::hay_block;
Block* Block::carpet;
Block* Block::hardened_clay;
Block* Block::coal_block;
Block* Block::packed_ice;
Block* Block::double_plant;
Block* Block::standing_banner;
Block* Block::wall_banner;
Block* Block::daylight_detector_inverted;
Block* Block::red_sandstone;
Block* Block::red_sandstone_stairs;
Block* Block::double_stone_slab2;
Block* Block::stone_slab2;
Block* Block::spruce_fence_gate;
Block* Block::birch_fence_gate;
Block* Block::jungle_fence_gate;
Block* Block::dark_oak_fence_gate;
Block* Block::acacia_fence_gate;
Block* Block::spruce_fence;
Block* Block::birch_fence;
Block* Block::jungle_fence;
Block* Block::dark_oak_fence;
Block* Block::acacia_fence;
Block* Block::spruce_door;
Block* Block::birch_door;
Block* Block::jungle_door;
Block* Block::acacia_door;
Block* Block::dark_oak_door;

void Block::registerBlock(ushort_t type, string_t name, Block *block) {
    typeToBlock[type] = block;
    nameToBlock[name] = block;
    blockToType[block] = type;
    nameToType[name] = type;
    blockToName[block] = name;
    typeToName[type] = name;
}

void Block::registerBlocks() {
    Material::registerMaterials();
    registerBlock(0, "air", air = new BlockAir());
    registerBlock(1, "stone", stone = new Block());
    registerBlock(2, "grass", grass = new Block());
    registerBlock(3, "dirt", dirt = new Block());
    registerBlock(4, "cobblestone", cobblestone = new Block(Material::rock));
    registerBlock(5, "planks", planks = new Block());
    registerBlock(6, "sapling", sapling = new Block());
    registerBlock(7, "bedrock", bedrock = new Block(Material::rock));
    registerBlock(8, "flowing_water", flowing_water = new Block());
    registerBlock(9, "water", water = new Block());
    registerBlock(10, "flowing_lava", flowing_lava = new Block());
    registerBlock(11, "lava", lava = new Block());
    registerBlock(12, "sand", sand = new Block());
    registerBlock(13, "gravel", gravel = new Block());
    registerBlock(14, "gold_ore", gold_ore = new Block());
    registerBlock(15, "iron_ore", iron_ore = new Block());
    registerBlock(16, "coal_ore", coal_ore = new Block());
    registerBlock(17, "log", log = new Block());
    registerBlock(18, "leaves", leaves = new Block());
    registerBlock(19, "sponge", sponge = new Block());
    registerBlock(20, "glass", glass = new Block());
    registerBlock(21, "lapis_ore", lapis_ore = new Block());
    registerBlock(22, "lapis_block", lapis_block = new Block());
    registerBlock(23, "dispenser", dispenser = new Block());
    registerBlock(24, "sandstone", sandstone = new Block());
    registerBlock(25, "noteblock", noteblock = new Block());
    registerBlock(26, "bed", bed = new Block());
    registerBlock(27, "golden_rail", golden_rail = new Block());
    registerBlock(28, "detector_rail", detector_rail = new Block());
    registerBlock(29, "sticky_piston", sticky_piston = new Block());
    registerBlock(30, "web", web = new Block());
    registerBlock(31, "tallgrass", tallgrass = new Block());
    registerBlock(32, "deadbush", deadbush = new Block());
    registerBlock(33, "piston", piston = new Block());
    registerBlock(34, "piston_head", piston_head = new Block());
    registerBlock(35, "wool", wool = new Block());
    registerBlock(36, "piston_extension", piston_extension = new Block());
    registerBlock(37, "yellow_flower", yellow_flower = new Block());
    registerBlock(38, "red_flower", red_flower = new Block());
    registerBlock(39, "brown_mushroom", brown_mushroom = new Block());
    registerBlock(40, "red_mushroom", red_mushroom = new Block());
    registerBlock(41, "gold_block", gold_block = new Block());
    registerBlock(42, "iron_block", iron_block = new Block());
    registerBlock(43, "double_stone_slab", double_stone_slab = new Block());
    registerBlock(44, "stone_slab", stone_slab = new Block());
    registerBlock(45, "brick_block", brick_block = new Block(Material::rock));
    registerBlock(46, "tnt", tnt = new Block());
    registerBlock(47, "bookshelf", bookshelf = new Block());
    registerBlock(48, "mossy_cobblestone", mossy_cobblestone = new Block(Material::rock));
    registerBlock(49, "obsidian", obsidian = new Block());
    registerBlock(50, "torch", torch = new Block());
    registerBlock(51, "fire", fire = new Block());
    registerBlock(52, "mob_spawner", mob_spawner = new Block());
    registerBlock(53, "oak_stairs", oak_stairs = new Block());
    registerBlock(54, "chest", chest = new Block());
    registerBlock(55, "redstone_wire", redstone_wire = new Block());
    registerBlock(56, "diamond_ore", diamond_ore = new Block());
    registerBlock(57, "diamond_block", diamond_block = new Block());
    registerBlock(58, "crafting_table", crafting_table = new Block());
    registerBlock(59, "wheat", wheat = new Block());
    registerBlock(60, "farmland", farmland = new Block());
    registerBlock(61, "furnace", furnace = new Block());
    registerBlock(62, "lit_furnace", lit_furnace = new Block());
    registerBlock(63, "standing_sign", standing_sign = new Block());
    registerBlock(64, "wooden_door", wooden_door = new Block());
    registerBlock(65, "ladder", ladder = new Block());
    registerBlock(66, "rail", rail = new Block());
    registerBlock(67, "stone_stairs", stone_stairs = new Block());
    registerBlock(68, "wall_sign", wall_sign = new Block());
    registerBlock(69, "lever", lever = new Block());
    registerBlock(70, "stone_pressure_plate", stone_pressure_plate = new Block());
    registerBlock(71, "iron_door", iron_door = new Block());
    registerBlock(72, "wooden_pressure_plate", wooden_pressure_plate = new Block());
    registerBlock(73, "redstone_ore", redstone_ore = new Block());
    registerBlock(74, "lit_redstone_ore", lit_redstone_ore = new Block());
    registerBlock(75, "unlit_redstone_torch", unlit_redstone_torch = new Block());
    registerBlock(76, "redstone_torch", redstone_torch = new Block());
    registerBlock(77, "stone_button", stone_button = new Block());
    registerBlock(78, "snow_layer", snow_layer = new Block());
    registerBlock(79, "ice", ice = new Block());
    registerBlock(80, "snow", snow = new Block());
    registerBlock(81, "cactus", cactus = new Block());
    registerBlock(82, "clay", clay = new Block());
    registerBlock(83, "reeds", reeds = new Block());
    registerBlock(84, "jukebox", jukebox = new Block());
    registerBlock(85, "fence", oak_fence = new Block());
    registerBlock(86, "pumpkin", pumpkin = new Block());
    registerBlock(87, "netherrack", netherrack = new Block());
    registerBlock(88, "soul_sand", soul_sand = new Block());
    registerBlock(89, "glowstone", glowstone = new Block());
    registerBlock(90, "portal", portal = new Block());
    registerBlock(91, "lit_pumpkin", lit_pumpkin = new Block());
    registerBlock(92, "cake", cake = new Block());
    registerBlock(93, "unpowered_repeater", unpowered_repeater = new Block());
    registerBlock(94, "powered_repeater", powered_repeater = new Block());
    registerBlock(95, "stained_glass", stained_glass = new Block());
    registerBlock(96, "trapdoor", trapdoor = new Block());
    registerBlock(97, "monster_egg", monster_egg = new Block());
    registerBlock(98, "stonebrick", stonebrick = new Block());
    registerBlock(99, "brown_mushroom_block", brown_mushroom_block = new Block());
    registerBlock(100, "red_mushroom_block", red_mushroom_block = new Block());
    registerBlock(101, "iron_bars", iron_bars = new Block());
    registerBlock(102, "glass_pane", glass_pane = new Block());
    registerBlock(103, "melon_block", melon_block = new Block());
    registerBlock(104, "pumpkin_stem", pumpkin_stem = new Block());
    registerBlock(105, "melon_stem", melon_stem = new Block());
    registerBlock(106, "vine", vine = new Block());
    registerBlock(107, "fence_gate", oak_fence_gate = new Block());
    registerBlock(108, "brick_stairs", brick_stairs = new Block());
    registerBlock(109, "stone_brick_stairs", stone_brick_stairs = new Block());
    registerBlock(110, "mycelium", mycelium = new Block());
    registerBlock(111, "waterlily", waterlily = new Block());
    registerBlock(112, "nether_brick", nether_brick = new Block());
    registerBlock(113, "nether_brick_fence", nether_brick_fence = new Block());
    registerBlock(114, "nether_brick_stairs", nether_brick_stairs = new Block());
    registerBlock(115, "nether_wart", nether_wart = new Block());
    registerBlock(116, "enchanting_table", enchanting_table = new Block());
    registerBlock(117, "brewing_stand", brewing_stand = new Block());
    registerBlock(118, "cauldron", cauldron = new Block());
    registerBlock(119, "end_portal", end_portal = new Block());
    registerBlock(120, "end_portal_frame", end_portal_frame = new Block());
    registerBlock(121, "end_stone", end_stone = new Block(Material::rock));
    registerBlock(122, "dragon_egg", dragon_egg = new Block());
    registerBlock(123, "redstone_lamp", redstone_lamp = new Block());
    registerBlock(124, "lit_redstone_lamp", lit_redstone_lamp = new Block());
    registerBlock(125, "double_wooden_slab", double_wooden_slab = new Block());
    registerBlock(126, "wooden_slab", wooden_slab = new Block());
    registerBlock(127, "cocoa", cocoa = new Block());
    registerBlock(128, "sandstone_stairs", sandstone_stairs = new Block());
    registerBlock(129, "emerald_ore", emerald_ore = new Block());
    registerBlock(130, "ender_chest", ender_chest = new Block());
    registerBlock(131, "tripwire_hook", tripwire_hook = new Block());
    registerBlock(132, "tripwire", tripwire = new Block());
    registerBlock(133, "emerald_block", emerald_block = new Block());
    registerBlock(134, "spruce_stairs", spruce_stairs = new Block());
    registerBlock(135, "birch_stairs", birch_stairs = new Block());
    registerBlock(136, "jungle_stairs", jungle_stairs = new Block());
    registerBlock(137, "command_block", command_block = new Block());
    registerBlock(138, "beacon", beacon = new Block());
    registerBlock(139, "cobblestone_wall", cobblestone_wall = new Block());
    registerBlock(140, "flower_pot", flower_pot = new Block());
    registerBlock(141, "carrots", carrots = new Block());
    registerBlock(142, "potatoes", potatoes = new Block());
    registerBlock(143, "wooden_button", wooden_button = new Block());
    registerBlock(144, "skull", skull = new Block());
    registerBlock(145, "anvil", anvil = new Block());
    registerBlock(146, "trapped_chest", trapped_chest = new Block());
    registerBlock(147, "light_weighted_pressure_plate", light_weighted_pressure_plate = new Block());
    registerBlock(148, "heavy_weighted_pressure_plate", heavy_weighted_pressure_plate = new Block());
    registerBlock(149, "unpowered_comparator", unpowered_comparator = new Block());
    registerBlock(150, "powered_comparator", powered_comparator = new Block());
    registerBlock(151, "daylight_detector", daylight_detector = new Block());
    registerBlock(152, "redstone_block", redstone_block = new Block());
    registerBlock(153, "quartz_ore", quartz_ore = new Block());
    registerBlock(154, "hopper", hopper = new Block());
    registerBlock(155, "quartz_block", quartz_block = new Block());
    registerBlock(156, "quartz_stairs", quartz_stairs = new Block());
    registerBlock(157, "activator_rail", activator_rail = new Block());
    registerBlock(158, "dropper", dropper = new Block());
    registerBlock(159, "stained_hardened_clay", stained_hardened_clay = new Block());
    registerBlock(160, "stained_glass_pane", stained_glass_pane = new Block());
    registerBlock(161, "leaves2", leaves2 = new Block());
    registerBlock(162, "log2", log2 = new Block());
    registerBlock(163, "acacia_stairs", acacia_stairs = new Block());
    registerBlock(164, "dark_oak_stairs", dark_oak_stairs = new Block());
    registerBlock(165, "slime", slime_block = new Block());
    registerBlock(166, "barrier", barrier = new Block());
    registerBlock(167, "iron_trapdoor", iron_trapdoor = new Block());
    registerBlock(168, "prismarine", prismarine = new Block());
    registerBlock(169, "sea_lantern", sea_lantern = new Block());
    registerBlock(170, "hay_block", hay_block = new Block());
    registerBlock(171, "carpet", carpet = new Block());
    registerBlock(172, "hardened_clay", hardened_clay = new Block());
    registerBlock(173, "coal_block", coal_block = new Block(Material::rock));
    registerBlock(174, "packed_ice", packed_ice = new Block());
    registerBlock(175, "double_plant", double_plant = new Block());
    registerBlock(176, "standing_banner", standing_banner = new Block());
    registerBlock(177, "wall_banner", wall_banner = new Block());
    registerBlock(178, "daylight_detector_inverted", daylight_detector_inverted = new Block());
    registerBlock(179, "red_sandstone", red_sandstone = new Block());
    registerBlock(180, "red_sandstone_stairs", red_sandstone_stairs = new Block());
    registerBlock(181, "double_stone_slab2", double_stone_slab2 = new Block());
    registerBlock(182, "stone_slab2", stone_slab2 = new Block());
    registerBlock(183, "spruce_fence_gate", spruce_fence_gate = new Block());
    registerBlock(184, "birch_fence_gate", birch_fence_gate = new Block());
    registerBlock(185, "jungle_fence_gate", jungle_fence_gate = new Block());
    registerBlock(186, "dark_oak_fence_gate", dark_oak_fence_gate = new Block());
    registerBlock(187, "acacia_fence_gate", acacia_fence_gate = new Block());
    registerBlock(188, "spruce_fence", spruce_fence = new Block());
    registerBlock(189, "birch_fence", birch_fence = new Block());
    registerBlock(190, "jungle_fence", jungle_fence = new Block());
    registerBlock(191, "dark_oak_fence", dark_oak_fence = new Block());
    registerBlock(192, "acacia_fence", acacia_fence = new Block());
    registerBlock(193, "spruce_door", spruce_door = new Block());
    registerBlock(194, "birch_door", birch_door = new Block());
    registerBlock(195, "jungle_door", jungle_door = new Block());
    registerBlock(196, "acacia_door", acacia_door = new Block());
    registerBlock(197, "dark_oak_door", dark_oak_door = new Block());
}

void Block::deregisterBlocks() {
    std::unordered_map<string_t, Block*>::iterator it;
    for (it = nameToBlock.begin(); it != nameToBlock.end(); ++it)
        delete it->second;
    Material::deregisterMaterials();
}

Block *Block::getBlock(ushort_t type) {
    return typeToBlock[type];
}

Block *Block::getBlock(string_t name) {
    return nameToBlock[name];
}

ushort_t Block::getBlockType(Block *block) {
    return blockToType[block];
}

ushort_t Block::getBlockType(string_t name) {
    return nameToType[name];
}

string_t Block::getBlockName(Block *block) {
    return blockToName[block];
}

string_t Block::getBlockName(ushort_t type) {
    return typeToName[type];
}

Block::Block() : Block(Material::rock) {}

Block::Block(Material *material) : material(material), boundingBox({0, 0, 0, 1, 1, 1}) {}

Material *Block::getMaterial() {
    return material;
}

AxisAlignedBB Block::getBoundingBox() {
    return boundingBox;
}

std::unordered_map<ushort_t, Block*> Block::typeToBlock;
std::unordered_map<string_t, Block*> Block::nameToBlock;
std::unordered_map<Block*, ushort_t> Block::blockToType;
std::unordered_map<string_t, ushort_t> Block::nameToType;
std::unordered_map<Block*, string_t> Block::blockToName;
std::unordered_map<ushort_t, string_t> Block::typeToName;
