#include "Block.h"

Block* Block::air = new Block();
Block* Block::stone = new Block();
Block* Block::grass = new Block();
Block* Block::dirt = new Block();
Block* Block::cobblestone = new Block();
Block* Block::planks = new Block();
Block* Block::sapling = new Block();
Block* Block::bedrock = new Block();
Block* Block::flowing_water = new Block();
Block* Block::water = new Block();
Block* Block::flowing_lava = new Block();
Block* Block::lava = new Block();
Block* Block::sand = new Block();
Block* Block::gravel = new Block();
Block* Block::gold_ore = new Block();
Block* Block::iron_ore = new Block();
Block* Block::coal_ore = new Block();
Block* Block::log = new Block();
Block* Block::leaves = new Block();
Block* Block::sponge = new Block();
Block* Block::glass = new Block();
Block* Block::lapis_ore = new Block();
Block* Block::lapis_block = new Block();
Block* Block::dispenser = new Block();
Block* Block::sandstone = new Block();
Block* Block::noteblock = new Block();
Block* Block::bed = new Block();
Block* Block::golden_rail = new Block();
Block* Block::detector_rail = new Block();
Block* Block::sticky_piston = new Block();
Block* Block::web = new Block();
Block* Block::tallgrass = new Block();
Block* Block::deadbush = new Block();
Block* Block::piston = new Block();
Block* Block::piston_head = new Block();
Block* Block::wool = new Block();
Block* Block::piston_extension = new Block();
Block* Block::yellow_flower = new Block();
Block* Block::red_flower = new Block();
Block* Block::brown_mushroom = new Block();
Block* Block::red_mushroom = new Block();
Block* Block::gold_block = new Block();
Block* Block::iron_block = new Block();
Block* Block::double_stone_slab = new Block();
Block* Block::stone_slab = new Block();
Block* Block::brick_block = new Block();
Block* Block::tnt = new Block();
Block* Block::bookshelf = new Block();
Block* Block::mossy_cobblestone = new Block();
Block* Block::obsidian = new Block();
Block* Block::torch = new Block();
Block* Block::fire = new Block();
Block* Block::mob_spawner = new Block();
Block* Block::oak_stairs = new Block();
Block* Block::chest = new Block();
Block* Block::redstone_wire = new Block();
Block* Block::diamond_ore = new Block();
Block* Block::diamond_block = new Block();
Block* Block::crafting_table = new Block();
Block* Block::wheat = new Block();
Block* Block::farmland = new Block();
Block* Block::furnace = new Block();
Block* Block::lit_furnace = new Block();
Block* Block::standing_sign = new Block();
Block* Block::wooden_door = new Block();
Block* Block::ladder = new Block();
Block* Block::rail = new Block();
Block* Block::stone_stairs = new Block();
Block* Block::wall_sign = new Block();
Block* Block::lever = new Block();
Block* Block::stone_pressure_plate = new Block();
Block* Block::iron_door = new Block();
Block* Block::wooden_pressure_plate = new Block();
Block* Block::redstone_ore = new Block();
Block* Block::lit_redstone_ore = new Block();
Block* Block::unlit_redstone_torch = new Block();
Block* Block::redstone_torch = new Block();
Block* Block::stone_button = new Block();
Block* Block::snow_layer = new Block();
Block* Block::ice = new Block();
Block* Block::snow = new Block();
Block* Block::cactus = new Block();
Block* Block::clay = new Block();
Block* Block::reeds = new Block();
Block* Block::jukebox = new Block();
Block* Block::fence = new Block();
Block* Block::pumpkin = new Block();
Block* Block::netherrack = new Block();
Block* Block::soul_sand = new Block();
Block* Block::glowstone = new Block();
Block* Block::portal = new Block();
Block* Block::lit_pumpkin = new Block();
Block* Block::cake = new Block();
Block* Block::unpowered_repeater = new Block();
Block* Block::powered_repeater = new Block();
Block* Block::stained_glass = new Block();
Block* Block::trapdoor = new Block();
Block* Block::monster_egg = new Block();
Block* Block::stonebrick = new Block();
Block* Block::brown_mushroom_block = new Block();
Block* Block::red_mushroom_block = new Block();
Block* Block::iron_bars = new Block();
Block* Block::glass_pane = new Block();
Block* Block::melon_block = new Block();
Block* Block::pumpkin_stem = new Block();
Block* Block::melon_stem = new Block();
Block* Block::vine = new Block();
Block* Block::fence_gate = new Block();
Block* Block::brick_stairs = new Block();
Block* Block::stone_brick_stairs = new Block();
Block* Block::mycelium = new Block();
Block* Block::waterlily = new Block();
Block* Block::nether_brick = new Block();
Block* Block::nether_brick_fence = new Block();
Block* Block::nether_brick_stairs = new Block();
Block* Block::nether_wart = new Block();
Block* Block::enchanting_table = new Block();
Block* Block::brewing_stand = new Block();
Block* Block::cauldron = new Block();
Block* Block::end_portal = new Block();
Block* Block::end_portal_frame = new Block();
Block* Block::end_stone = new Block();
Block* Block::dragon_egg = new Block();
Block* Block::redstone_lamp = new Block();
Block* Block::lit_redstone_lamp = new Block();
Block* Block::double_wooden_slab = new Block();
Block* Block::wooden_slab = new Block();
Block* Block::cocoa = new Block();
Block* Block::sandstone_stairs = new Block();
Block* Block::emerald_ore = new Block();
Block* Block::ender_chest = new Block();
Block* Block::tripwire_hook = new Block();
Block* Block::tripwire = new Block();
Block* Block::emerald_block = new Block();
Block* Block::spruce_stairs = new Block();
Block* Block::birch_stairs = new Block();
Block* Block::jungle_stairs = new Block();
Block* Block::command_block = new Block();
Block* Block::beacon = new Block();
Block* Block::cobblestone_wall = new Block();
Block* Block::flower_pot = new Block();
Block* Block::carrots = new Block();
Block* Block::potatoes = new Block();
Block* Block::wooden_button = new Block();
Block* Block::skull = new Block();
Block* Block::anvil = new Block();
Block* Block::trapped_chest = new Block();
Block* Block::light_weighted_pressure_plate = new Block();
Block* Block::heavy_weighted_pressure_plate = new Block();
Block* Block::unpowered_comparator = new Block();
Block* Block::powered_comparator = new Block();
Block* Block::daylight_detector = new Block();
Block* Block::redstone_block = new Block();
Block* Block::quartz_ore = new Block();
Block* Block::hopper = new Block();
Block* Block::quartz_block = new Block();
Block* Block::quartz_stairs = new Block();
Block* Block::activator_rail = new Block();
Block* Block::dropper = new Block();
Block* Block::stained_hardened_clay = new Block();
Block* Block::stained_glass_pane = new Block();
Block* Block::leaves2 = new Block();
Block* Block::log2 = new Block();
Block* Block::acacia_stairs = new Block();
Block* Block::dark_oak_stairs = new Block();
Block* Block::slime = new Block();
Block* Block::barrier = new Block();
Block* Block::iron_trapdoor = new Block();
Block* Block::prismarine = new Block();
Block* Block::sea_lantern = new Block();
Block* Block::hay_bale = new Block();
Block* Block::carpet = new Block();
Block* Block::hardened_clay = new Block();
Block* Block::coal_block = new Block();
Block* Block::packed_ice = new Block();
Block* Block::double_plant = new Block();
Block* Block::standing_banner = new Block();
Block* Block::wall_banner = new Block();
Block* Block::daylight_detector_inverted = new Block();
Block* Block::red_sandstone = new Block();
Block* Block::red_sandstone_stairs = new Block();
Block* Block::double_stone_slab2 = new Block();
Block* Block::stone_slab2 = new Block();
Block* Block::spruce_fence_gate = new Block();
Block* Block::birch_fence_gate = new Block();
Block* Block::jungle_fence_gate = new Block();
Block* Block::dark_oak_fence_gate = new Block();
Block* Block::acacia_fence_gate = new Block();
Block* Block::spruce_fence = new Block();
Block* Block::birch_fence = new Block();
Block* Block::jungle_fence = new Block();
Block* Block::dark_oak_fence = new Block();
Block* Block::acacia_fence = new Block();
Block* Block::spruce_door = new Block();
Block* Block::birch_door = new Block();
Block* Block::jungle_door = new Block();
Block* Block::acacia_door = new Block();
Block* Block::dark_oak_door = new Block();

void Block::registerBlocks() {
    registerBlock(0, "air", air);
    registerBlock(1, "stone", stone);
    registerBlock(2, "grass", grass);
    registerBlock(3, "dirt", dirt);
    registerBlock(4, "cobblestone", cobblestone);
    registerBlock(5, "planks", planks);
    registerBlock(6, "sapling", sapling);
    registerBlock(7, "bedrock", bedrock);
    registerBlock(8, "flowing_water", flowing_water);
    registerBlock(9, "water", water);
    registerBlock(10, "flowing_lava", flowing_lava);
    registerBlock(11, "lava", lava);
    registerBlock(12, "sand", sand);
    registerBlock(13, "gravel", gravel);
    registerBlock(14, "gold_ore", gold_ore);
    registerBlock(15, "iron_ore", iron_ore);
    registerBlock(16, "coal_ore", coal_ore);
    registerBlock(17, "log", log);
    registerBlock(18, "leaves", leaves);
    registerBlock(19, "sponge", sponge);
    registerBlock(20, "glass", glass);
    registerBlock(21, "lapis_ore", lapis_ore);
    registerBlock(22, "lapis_block", lapis_block);
    registerBlock(23, "dispenser", dispenser);
    registerBlock(24, "sandstone", sandstone);
    registerBlock(25, "noteblock", noteblock);
    registerBlock(26, "bed", bed);
    registerBlock(27, "golden_rail", golden_rail);
    registerBlock(28, "detector_rail", detector_rail);
    registerBlock(29, "sticky_piston", sticky_piston);
    registerBlock(30, "web", web);
    registerBlock(31, "tallgrass", tallgrass);
    registerBlock(32, "deadbush", deadbush);
    registerBlock(33, "piston", piston);
    registerBlock(34, "piston_head", piston_head);
    registerBlock(35, "wool", wool);
    registerBlock(36, "piston_extension", piston_extension);
    registerBlock(37, "yellow_flower", yellow_flower);
    registerBlock(38, "red_flower", red_flower);
    registerBlock(39, "brown_mushroom", brown_mushroom);
    registerBlock(40, "red_mushroom", red_mushroom);
    registerBlock(41, "gold_block", gold_block);
    registerBlock(42, "iron_block", iron_block);
    registerBlock(43, "double_stone_slab", double_stone_slab);
    registerBlock(44, "stone_slab", stone_slab);
    registerBlock(45, "brick_block", brick_block);
    registerBlock(46, "tnt", tnt);
    registerBlock(47, "bookshelf", bookshelf);
    registerBlock(48, "mossy_cobblestone", mossy_cobblestone);
    registerBlock(49, "obsidian", obsidian);
    registerBlock(50, "torch", torch);
    registerBlock(51, "fire", fire);
    registerBlock(52, "mob_spawner", mob_spawner);
    registerBlock(53, "oak_stairs", oak_stairs);
    registerBlock(54, "chest", chest);
    registerBlock(55, "redstone_wire", redstone_wire);
    registerBlock(56, "diamond_ore", diamond_ore);
    registerBlock(57, "diamond_block", diamond_block);
    registerBlock(58, "crafting_table", crafting_table);
    registerBlock(59, "wheat", wheat);
    registerBlock(60, "farmland", farmland);
    registerBlock(61, "furnace", furnace);
    registerBlock(62, "lit_furnace", lit_furnace);
    registerBlock(63, "standing_sign", standing_sign);
    registerBlock(64, "wooden_door", wooden_door);
    registerBlock(65, "ladder", ladder);
    registerBlock(66, "rail", rail);
    registerBlock(67, "stone_stairs", stone_stairs);
    registerBlock(68, "wall_sign", wall_sign);
    registerBlock(69, "lever", lever);
    registerBlock(70, "stone_pressure_plate", stone_pressure_plate);
    registerBlock(71, "iron_door", iron_door);
    registerBlock(72, "wooden_pressure_plate", wooden_pressure_plate);
    registerBlock(73, "redstone_ore", redstone_ore);
    registerBlock(74, "lit_redstone_ore", lit_redstone_ore);
    registerBlock(75, "unlit_redstone_torch", unlit_redstone_torch);
    registerBlock(76, "redstone_torch", redstone_torch);
    registerBlock(77, "stone_button", stone_button);
    registerBlock(78, "snow_layer", snow_layer);
    registerBlock(79, "ice", ice);
    registerBlock(80, "snow", snow);
    registerBlock(81, "cactus", cactus);
    registerBlock(82, "clay", clay);
    registerBlock(83, "reeds", reeds);
    registerBlock(84, "jukebox", jukebox);
    registerBlock(85, "fence", fence);
    registerBlock(86, "pumpkin", pumpkin);
    registerBlock(87, "netherrack", netherrack);
    registerBlock(88, "soul_sand", soul_sand);
    registerBlock(89, "glowstone", glowstone);
    registerBlock(90, "portal", portal);
    registerBlock(91, "lit_pumpkin", lit_pumpkin);
    registerBlock(92, "cake", cake);
    registerBlock(93, "unpowered_repeater", unpowered_repeater);
    registerBlock(94, "powered_repeater", powered_repeater);
    registerBlock(95, "stained_glass", stained_glass);
    registerBlock(96, "trapdoor", trapdoor);
    registerBlock(97, "monster_egg", monster_egg);
    registerBlock(98, "stonebrick", stonebrick);
    registerBlock(99, "brown_mushroom_block", brown_mushroom_block);
    registerBlock(100, "red_mushroom_block", red_mushroom_block);
    registerBlock(101, "iron_bars", iron_bars);
    registerBlock(102, "glass_pane", glass_pane);
    registerBlock(103, "melon_block", melon_block);
    registerBlock(104, "pumpkin_stem", pumpkin_stem);
    registerBlock(105, "melon_stem", melon_stem);
    registerBlock(106, "vine", vine);
    registerBlock(107, "fence_gate", fence_gate);
    registerBlock(108, "brick_stairs", brick_stairs);
    registerBlock(109, "stone_brick_stairs", stone_brick_stairs);
    registerBlock(110, "mycelium", mycelium);
    registerBlock(111, "waterlily", waterlily);
    registerBlock(112, "nether_brick", nether_brick);
    registerBlock(113, "nether_brick_fence", nether_brick_fence);
    registerBlock(114, "nether_brick_stairs", nether_brick_stairs);
    registerBlock(115, "nether_wart", nether_wart);
    registerBlock(116, "enchanting_table", enchanting_table);
    registerBlock(117, "brewing_stand", brewing_stand);
    registerBlock(118, "cauldron", cauldron);
    registerBlock(119, "end_portal", end_portal);
    registerBlock(120, "end_portal_frame", end_portal_frame);
    registerBlock(121, "end_stone", end_stone);
    registerBlock(122, "dragon_egg", dragon_egg);
    registerBlock(123, "redstone_lamp", redstone_lamp);
    registerBlock(124, "lit_redstone_lamp", lit_redstone_lamp);
    registerBlock(125, "double_wooden_slab", double_wooden_slab);
    registerBlock(126, "wooden_slab", wooden_slab);
    registerBlock(127, "cocoa", cocoa);
    registerBlock(128, "sandstone_stairs", sandstone_stairs);
    registerBlock(129, "emerald_ore", emerald_ore);
    registerBlock(130, "ender_chest", ender_chest);
    registerBlock(131, "tripwire_hook", tripwire_hook);
    registerBlock(132, "tripwire", tripwire);
    registerBlock(133, "emerald_block", emerald_block);
    registerBlock(134, "spruce_stairs", spruce_stairs);
    registerBlock(135, "birch_stairs", birch_stairs);
    registerBlock(136, "jungle_stairs", jungle_stairs);
    registerBlock(137, "command_block", command_block);
    registerBlock(138, "beacon", beacon);
    registerBlock(139, "cobblestone_wall", cobblestone_wall);
    registerBlock(140, "flower_pot", flower_pot);
    registerBlock(141, "carrots", carrots);
    registerBlock(142, "potatoes", potatoes);
    registerBlock(143, "wooden_button", wooden_button);
    registerBlock(144, "skull", skull);
    registerBlock(145, "anvil", anvil);
    registerBlock(146, "trapped_chest", trapped_chest);
    registerBlock(147, "light_weighted_pressure_plate", light_weighted_pressure_plate);
    registerBlock(148, "heavy_weighted_pressure_plate", heavy_weighted_pressure_plate);
    registerBlock(149, "unpowered_comparator", unpowered_comparator);
    registerBlock(150, "powered_comparator", powered_comparator);
    registerBlock(151, "daylight_detector", daylight_detector);
    registerBlock(152, "redstone_block", redstone_block);
    registerBlock(153, "quartz_ore", quartz_ore);
    registerBlock(154, "hopper", hopper);
    registerBlock(155, "quartz_block", quartz_block);
    registerBlock(156, "quartz_stairs", quartz_stairs);
    registerBlock(157, "activator_rail", activator_rail);
    registerBlock(158, "dropper", dropper);
    registerBlock(159, "stained_hardened_clay", stained_hardened_clay);
    registerBlock(160, "stained_glass_pane", stained_glass_pane);
    registerBlock(161, "leaves2", leaves2);
    registerBlock(162, "log2", log2);
    registerBlock(163, "acacia_stairs", acacia_stairs);
    registerBlock(164, "dark_oak_stairs", dark_oak_stairs);
    registerBlock(165, "slime", slime);
    registerBlock(166, "barrier", barrier);
    registerBlock(167, "iron_trapdoor", iron_trapdoor);
    registerBlock(168, "prismarine", prismarine);
    registerBlock(169, "sea_lantern", sea_lantern);
    registerBlock(170, "hay_bale", hay_bale);
    registerBlock(171, "carpet", carpet);
    registerBlock(172, "hardened_clay", hardened_clay);
    registerBlock(173, "coal_block", coal_block);
    registerBlock(174, "packed_ice", packed_ice);
    registerBlock(175, "double_plant", double_plant);
    registerBlock(176, "standing_banner", standing_banner);
    registerBlock(177, "wall_banner", wall_banner);
    registerBlock(178, "daylight_detector_inverted", daylight_detector_inverted);
    registerBlock(179, "red_sandstone", red_sandstone);
    registerBlock(180, "red_sandstone_stairs", red_sandstone_stairs);
    registerBlock(181, "double_stone_slab2", double_stone_slab2);
    registerBlock(182, "stone_slab2", stone_slab2);
    registerBlock(183, "spruce_fence_gate", spruce_fence_gate);
    registerBlock(184, "birch_fence_gate", birch_fence_gate);
    registerBlock(185, "jungle_fence_gate", jungle_fence_gate);
    registerBlock(186, "dark_oak_fence_gate", dark_oak_fence_gate);
    registerBlock(187, "acacia_fence_gate", acacia_fence_gate);
    registerBlock(188, "spruce_fence", spruce_fence);
    registerBlock(189, "birch_fence", birch_fence);
    registerBlock(190, "jungle_fence", jungle_fence);
    registerBlock(191, "dark_oak_fence", dark_oak_fence);
    registerBlock(192, "acacia_fence", acacia_fence);
    registerBlock(193, "spruce_door", spruce_door);
    registerBlock(194, "birch_door", birch_door);
    registerBlock(195, "jungle_door", jungle_door);
    registerBlock(196, "acacia_door", acacia_door);
    registerBlock(197, "dark_oak_door", dark_oak_door);
}

void Block::registerBlock(ubyte_t id, string_t name, Block *block) {
    idToName.insert({id, name});
    idToBlock.insert({id, block});
    nameToId.insert({name, id,});
    nameToBlock.insert({name, block});
}

void Block::deregisterBlocks() {
    std::unordered_map<string_t, Block*>::iterator it;
    for (it = nameToBlock.begin(); it != nameToBlock.end(); ++it)
        delete it->second;
}

Block *Block::getBlock(ubyte_t id) {
    return idToBlock[id];
}

Block *Block::getBlock(string_t name) {
    return nameToBlock[name];
}

ubyte_t Block::getBlockId(string_t name) {
    return nameToId[name];
}

string_t Block::getBlockName(ubyte_t id) {
    return idToName[id];
}

Block::Block() {}

std::unordered_map<ubyte_t, string_t> Block::idToName;
std::unordered_map<ubyte_t, Block*> Block::idToBlock;
std::unordered_map<string_t, ubyte_t> Block::nameToId;
std::unordered_map<string_t, Block*> Block::nameToBlock;
